[2024-04-11T16:30:08.846+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-11T16:30:08.903+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Process_W3_Data.DateTable manual__2024-04-11T16:29:48.873858+00:00 [queued]>
[2024-04-11T16:30:08.918+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Process_W3_Data.DateTable manual__2024-04-11T16:29:48.873858+00:00 [queued]>
[2024-04-11T16:30:08.918+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-11T16:30:08.944+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): DateTable> on 2024-04-11 16:29:48.873858+00:00
[2024-04-11T16:30:08.960+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=22477) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-11T16:30:08.968+0000] {standard_task_runner.py:63} INFO - Started process 22480 to run task
[2024-04-11T16:30:08.981+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Process_W3_Data', 'DateTable', 'manual__2024-04-11T16:29:48.873858+00:00', '--job-id', '145', '--raw', '--subdir', 'DAGS_FOLDER/w3c.py', '--cfg-path', '/tmp/tmpqjj7w9gq']
[2024-04-11T16:30:08.990+0000] {standard_task_runner.py:91} INFO - Job 145: Subtask DateTable
[2024-04-11T16:30:09.118+0000] {task_command.py:426} INFO - Running <TaskInstance: Process_W3_Data.DateTable manual__2024-04-11T16:29:48.873858+00:00 [running]> on host 426f0b9f9d71
[2024-04-11T16:30:09.366+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Process_W3_Data' AIRFLOW_CTX_TASK_ID='DateTable' AIRFLOW_CTX_EXECUTION_DATE='2024-04-11T16:29:48.873858+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-11T16:29:48.873858+00:00'
[2024-04-11T16:30:09.370+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-11T16:30:09.703+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-04-11T16:30:09.704+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-11T16:30:09.732+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=Process_W3_Data, task_id=DateTable, execution_date=20240411T162948, start_date=20240411T163008, end_date=20240411T163009
[2024-04-11T16:30:09.863+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-11T16:30:09.973+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-04-11T16:30:09.975+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
